# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/storage/db/schema.rs"

# TODO: uncomment when supported
#       https://github.com/diesel-rs/diesel/issues/2163
#       workaround: diesel migration redo --migration-dir src/storage/db/migrations/
# [migrations_directory]
# dir = "src/storage/db/migrations/"
